import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

/**
 * Avatar Presets Seed Data
 *
 * 25 high-quality preset avatars across 5 categories
 * Each preset includes persona + visual attributes for consistent generation
 */

const presets = [
  // ========================================
  // PROFESSIONAL (8 presets)
  // ========================================
  {
    name: 'Professional Business Woman',
    description: 'Confident Asian business woman in modern office attire',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-woman-asian.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-woman-asian-thumb.jpg',
    generationPrompt: 'professional portrait of confident Asian business woman in elegant blazer, modern office setting',
    personaName: 'Sarah Chen',
    personaAge: 32,
    personaPersonality: JSON.stringify(['professional', 'confident', 'approachable']),
    personaBackground: 'Senior Marketing Executive with 10 years experience',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'east-asian',
    bodyType: 'average',
    hairStyle: 'straight long',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light-medium',
    style: 'professional',
  },
  {
    name: 'Professional Business Man',
    description: 'Charismatic business executive in formal suit',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-man-caucasian.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-man-caucasian-thumb.jpg',
    generationPrompt: 'professional headshot of charismatic Caucasian businessman in navy suit and tie, corporate environment',
    personaName: 'James Anderson',
    personaAge: 38,
    personaPersonality: JSON.stringify(['charismatic', 'strategic', 'professional']),
    personaBackground: 'Tech startup CEO and entrepreneur',
    gender: 'male',
    ageRange: 'adult',
    ethnicity: 'caucasian',
    bodyType: 'athletic',
    hairStyle: 'short modern',
    hairColor: 'brown',
    eyeColor: 'blue',
    skinTone: 'fair',
    style: 'formal',
  },
  {
    name: 'Professional Hijabi Woman',
    description: 'Elegant Indonesian professional with modern hijab',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-hijabi.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-hijabi-thumb.jpg',
    generationPrompt: 'professional portrait of elegant Indonesian woman with modern pastel hijab, wearing professional blazer, warm smile',
    personaName: 'Aisha Rahman',
    personaAge: 28,
    personaPersonality: JSON.stringify(['professional', 'friendly', 'innovative']),
    personaBackground: 'Digital marketing specialist and content creator',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'southeast-asian',
    bodyType: 'average',
    hairStyle: 'hijab',
    hairColor: 'covered',
    eyeColor: 'dark brown',
    skinTone: 'medium',
    style: 'professional',
  },
  {
    name: 'Young Professional Developer',
    description: 'Tech-savvy developer in casual professional attire',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-developer.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-developer-thumb.jpg',
    generationPrompt: 'professional portrait of Indian software developer in smart casual attire, black-framed glasses, tech startup vibe',
    personaName: 'Raj Patel',
    personaAge: 26,
    personaPersonality: JSON.stringify(['innovative', 'focused', 'collaborative']),
    personaBackground: 'Full-stack developer at tech startup',
    gender: 'male',
    ageRange: 'young',
    ethnicity: 'south-asian',
    bodyType: 'slim',
    hairStyle: 'short neat',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium-tan',
    style: 'business-casual',
  },
  {
    name: 'Senior Executive Woman',
    description: 'Mature professional with executive presence',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-senior-woman.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-senior-woman-thumb.jpg',
    generationPrompt: 'professional portrait of mature Caucasian executive woman with silver hair, elegant suit, executive presence',
    personaName: 'Margaret Wilson',
    personaAge: 52,
    personaPersonality: JSON.stringify(['authoritative', 'strategic', 'mentoring']),
    personaBackground: 'Chief Operating Officer with 25 years experience',
    gender: 'female',
    ageRange: 'mature',
    ethnicity: 'caucasian',
    bodyType: 'average',
    hairStyle: 'short elegant',
    hairColor: 'silver',
    eyeColor: 'green',
    skinTone: 'fair',
    style: 'executive',
  },
  {
    name: 'Creative Professional',
    description: 'Artistic designer with creative flair',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-creative.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-creative-thumb.jpg',
    generationPrompt: 'professional portrait of African American creative designer in modern casual attire, artistic studio backdrop',
    personaName: 'Maya Johnson',
    personaAge: 29,
    personaPersonality: JSON.stringify(['creative', 'expressive', 'innovative']),
    personaBackground: 'UX/UI designer and digital artist',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'african',
    bodyType: 'average',
    hairStyle: 'natural curly',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'dark',
    style: 'creative-casual',
  },
  {
    name: 'Healthcare Professional',
    description: 'Caring medical professional in clinical setting',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-doctor.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-doctor-thumb.jpg',
    generationPrompt: 'professional portrait of Hispanic female doctor in white coat, stethoscope, warm caring expression, medical office',
    personaName: 'Dr. Sofia Martinez',
    personaAge: 35,
    personaPersonality: JSON.stringify(['caring', 'professional', 'knowledgeable']),
    personaBackground: 'General practitioner with focus on family medicine',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'hispanic',
    bodyType: 'average',
    hairStyle: 'medium wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'tan',
    style: 'medical',
  },
  {
    name: 'Financial Professional',
    description: 'Trustworthy financial advisor in formal attire',
    category: 'professional',
    imageUrl: '/presets/avatar-creator/professional-financial.jpg',
    thumbnailUrl: '/presets/avatar-creator/professional-financial-thumb.jpg',
    generationPrompt: 'professional portrait of Middle Eastern male financial advisor in formal suit, confident expression, office setting',
    personaName: 'Omar Hassan',
    personaAge: 42,
    personaPersonality: JSON.stringify(['trustworthy', 'analytical', 'professional']),
    personaBackground: 'Certified financial planner with 15 years experience',
    gender: 'male',
    ageRange: 'adult',
    ethnicity: 'middle-eastern',
    bodyType: 'average',
    hairStyle: 'short professional',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    style: 'formal',
  },

  // ========================================
  // CASUAL (6 presets)
  // ========================================
  {
    name: 'Casual Young Man',
    description: 'Friendly young man in casual everyday wear',
    category: 'casual',
    imageUrl: '/presets/avatar-creator/casual-young-man.jpg',
    thumbnailUrl: '/presets/avatar-creator/casual-young-man-thumb.jpg',
    generationPrompt: 'casual portrait of friendly Caucasian young man in t-shirt and jeans, relaxed smile, outdoor setting',
    personaName: 'Alex Thompson',
    personaAge: 24,
    personaPersonality: JSON.stringify(['friendly', 'laid-back', 'sociable']),
    personaBackground: 'College graduate and aspiring entrepreneur',
    gender: 'male',
    ageRange: 'young',
    ethnicity: 'caucasian',
    bodyType: 'athletic',
    hairStyle: 'messy modern',
    hairColor: 'light brown',
    eyeColor: 'hazel',
    skinTone: 'fair',
    style: 'casual',
  },
  {
    name: 'Casual Young Woman',
    description: 'Cheerful young woman in comfortable casual wear',
    category: 'casual',
    imageUrl: '/presets/avatar-creator/casual-young-woman.jpg',
    thumbnailUrl: '/presets/avatar-creator/casual-young-woman-thumb.jpg',
    generationPrompt: 'casual portrait of cheerful Asian young woman in cozy sweater, genuine smile, natural lighting',
    personaName: 'Emily Park',
    personaAge: 22,
    personaPersonality: JSON.stringify(['cheerful', 'energetic', 'friendly']),
    personaBackground: 'University student and part-time barista',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'east-asian',
    bodyType: 'slim',
    hairStyle: 'long straight',
    hairColor: 'dark brown',
    eyeColor: 'dark brown',
    skinTone: 'light',
    style: 'casual',
  },
  {
    name: 'Casual Hijabi Student',
    description: 'Cheerful Indonesian student with casual hijab',
    category: 'casual',
    imageUrl: '/presets/avatar-creator/casual-hijabi-student.jpg',
    thumbnailUrl: '/presets/avatar-creator/casual-hijabi-student-thumb.jpg',
    generationPrompt: 'casual portrait of cheerful Indonesian student with colorful hijab, casual sweater, friendly smile, campus backdrop',
    personaName: 'Dina Kartika',
    personaAge: 20,
    personaPersonality: JSON.stringify(['cheerful', 'studious', 'friendly']),
    personaBackground: 'Computer science student and tech enthusiast',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'southeast-asian',
    bodyType: 'slim',
    hairStyle: 'hijab',
    hairColor: 'covered',
    eyeColor: 'dark brown',
    skinTone: 'medium',
    style: 'casual',
  },
  {
    name: 'Casual Middle-aged Man',
    description: 'Relaxed middle-aged man in weekend wear',
    category: 'casual',
    imageUrl: '/presets/avatar-creator/casual-middle-man.jpg',
    thumbnailUrl: '/presets/avatar-creator/casual-middle-man-thumb.jpg',
    generationPrompt: 'casual portrait of relaxed African American middle-aged man in polo shirt, warm smile, outdoor setting',
    personaName: 'Marcus Brown',
    personaAge: 45,
    personaPersonality: JSON.stringify(['relaxed', 'wise', 'approachable']),
    personaBackground: 'High school teacher and weekend coach',
    gender: 'male',
    ageRange: 'mature',
    ethnicity: 'african',
    bodyType: 'average',
    hairStyle: 'short salt-pepper',
    hairColor: 'black-gray',
    eyeColor: 'dark brown',
    skinTone: 'dark',
    style: 'casual',
  },
  {
    name: 'Casual Artist',
    description: 'Creative artist in bohemian casual style',
    category: 'casual',
    imageUrl: '/presets/avatar-creator/casual-artist.jpg',
    thumbnailUrl: '/presets/avatar-creator/casual-artist-thumb.jpg',
    generationPrompt: 'casual portrait of creative Hispanic woman artist in bohemian style, long flowing hair, artistic expression',
    personaName: 'Isabella Rodriguez',
    personaAge: 30,
    personaPersonality: JSON.stringify(['creative', 'free-spirited', 'artistic']),
    personaBackground: 'Freelance illustrator and painter',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'hispanic',
    bodyType: 'slim',
    hairStyle: 'long wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'tan',
    style: 'bohemian',
  },
  {
    name: 'Casual Retiree',
    description: 'Active senior in comfortable casual wear',
    category: 'casual',
    imageUrl: '/presets/avatar-creator/casual-senior.jpg',
    thumbnailUrl: '/presets/avatar-creator/casual-senior-thumb.jpg',
    generationPrompt: 'casual portrait of active Caucasian senior woman in comfortable cardigan, warm smile, natural outdoor lighting',
    personaName: 'Helen White',
    personaAge: 65,
    personaPersonality: JSON.stringify(['warm', 'active', 'nurturing']),
    personaBackground: 'Retired teacher and volunteer community organizer',
    gender: 'female',
    ageRange: 'mature',
    ethnicity: 'caucasian',
    bodyType: 'average',
    hairStyle: 'short curly',
    hairColor: 'white',
    eyeColor: 'blue',
    skinTone: 'fair',
    style: 'casual-comfortable',
  },

  // ========================================
  // SPORTS (4 presets)
  // ========================================
  {
    name: 'Athletic Runner',
    description: 'Fit runner in athletic wear',
    category: 'sports',
    imageUrl: '/presets/avatar-creator/sports-runner.jpg',
    thumbnailUrl: '/presets/avatar-creator/sports-runner-thumb.jpg',
    generationPrompt: 'athletic portrait of fit Asian male runner in running gear, determined expression, outdoor athletic setting',
    personaName: 'Ken Tanaka',
    personaAge: 28,
    personaPersonality: JSON.stringify(['determined', 'disciplined', 'energetic']),
    personaBackground: 'Marathon runner and fitness coach',
    gender: 'male',
    ageRange: 'young',
    ethnicity: 'east-asian',
    bodyType: 'athletic',
    hairStyle: 'short sporty',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium',
    style: 'athletic',
  },
  {
    name: 'Fitness Instructor',
    description: 'Strong female fitness trainer',
    category: 'sports',
    imageUrl: '/presets/avatar-creator/sports-fitness-woman.jpg',
    thumbnailUrl: '/presets/avatar-creator/sports-fitness-woman-thumb.jpg',
    generationPrompt: 'athletic portrait of strong Hispanic female fitness instructor in gym wear, confident pose, gym environment',
    personaName: 'Carmen Silva',
    personaAge: 31,
    personaPersonality: JSON.stringify(['motivated', 'strong', 'inspiring']),
    personaBackground: 'Personal trainer and nutrition coach',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'hispanic',
    bodyType: 'athletic-toned',
    hairStyle: 'ponytail',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'tan',
    style: 'athletic',
  },
  {
    name: 'Yoga Instructor',
    description: 'Calm yoga practitioner in athletic wear',
    category: 'sports',
    imageUrl: '/presets/avatar-creator/sports-yoga.jpg',
    thumbnailUrl: '/presets/avatar-creator/sports-yoga-thumb.jpg',
    generationPrompt: 'serene portrait of Indian female yoga instructor in yoga attire, peaceful expression, studio setting',
    personaName: 'Priya Sharma',
    personaAge: 34,
    personaPersonality: JSON.stringify(['calm', 'balanced', 'mindful']),
    personaBackground: 'Certified yoga instructor and wellness coach',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'south-asian',
    bodyType: 'athletic',
    hairStyle: 'long straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium-tan',
    style: 'athletic-yoga',
  },
  {
    name: 'Athletic Coach',
    description: 'Experienced sports coach in team gear',
    category: 'sports',
    imageUrl: '/presets/avatar-creator/sports-coach.jpg',
    thumbnailUrl: '/presets/avatar-creator/sports-coach-thumb.jpg',
    generationPrompt: 'professional portrait of African American male sports coach in coaching attire, whistle around neck, motivational expression',
    personaName: 'Coach Davis',
    personaAge: 48,
    personaPersonality: JSON.stringify(['motivational', 'disciplined', 'strategic']),
    personaBackground: 'High school basketball coach with 20 years experience',
    gender: 'male',
    ageRange: 'mature',
    ethnicity: 'african',
    bodyType: 'athletic',
    hairStyle: 'short',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'dark',
    style: 'sports-coach',
  },

  // ========================================
  // FASHION (4 presets)
  // ========================================
  {
    name: 'Fashion Model',
    description: 'Elegant high fashion model',
    category: 'fashion',
    imageUrl: '/presets/avatar-creator/fashion-model.jpg',
    thumbnailUrl: '/presets/avatar-creator/fashion-model-thumb.jpg',
    generationPrompt: 'high fashion portrait of elegant Caucasian female model in designer clothing, professional makeup, studio lighting',
    personaName: 'Victoria Sterling',
    personaAge: 25,
    personaPersonality: JSON.stringify(['confident', 'elegant', 'poised']),
    personaBackground: 'International fashion model and brand ambassador',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'caucasian',
    bodyType: 'slim-tall',
    hairStyle: 'long straight',
    hairColor: 'blonde',
    eyeColor: 'blue',
    skinTone: 'fair',
    style: 'high-fashion',
  },
  {
    name: 'Street Fashion',
    description: 'Trendy street style enthusiast',
    category: 'fashion',
    imageUrl: '/presets/avatar-creator/fashion-street.jpg',
    thumbnailUrl: '/presets/avatar-creator/fashion-street-thumb.jpg',
    generationPrompt: 'trendy portrait of Korean young man in street fashion, modern hairstyle, urban backdrop',
    personaName: 'Jae Park',
    personaAge: 23,
    personaPersonality: JSON.stringify(['trendy', 'confident', 'creative']),
    personaBackground: 'Fashion blogger and style influencer',
    gender: 'male',
    ageRange: 'young',
    ethnicity: 'east-asian',
    bodyType: 'slim',
    hairStyle: 'modern stylish',
    hairColor: 'black-highlighted',
    eyeColor: 'dark brown',
    skinTone: 'light',
    style: 'street-fashion',
  },
  {
    name: 'Modest Fashion',
    description: 'Elegant modest fashion with hijab',
    category: 'fashion',
    imageUrl: '/presets/avatar-creator/fashion-modest.jpg',
    thumbnailUrl: '/presets/avatar-creator/fashion-modest-thumb.jpg',
    generationPrompt: 'elegant portrait of Middle Eastern woman in designer modest fashion, luxury hijab, sophisticated style',
    personaName: 'Amira Al-Farsi',
    personaAge: 27,
    personaPersonality: JSON.stringify(['elegant', 'sophisticated', 'confident']),
    personaBackground: 'Modest fashion designer and influencer',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'middle-eastern',
    bodyType: 'average',
    hairStyle: 'hijab-luxury',
    hairColor: 'covered',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    style: 'modest-luxury',
  },
  {
    name: 'Vintage Fashion',
    description: 'Classic vintage style enthusiast',
    category: 'fashion',
    imageUrl: '/presets/avatar-creator/fashion-vintage.jpg',
    thumbnailUrl: '/presets/avatar-creator/fashion-vintage-thumb.jpg',
    generationPrompt: 'vintage style portrait of African American woman in 1950s inspired fashion, classic hairstyle, retro aesthetic',
    personaName: 'Ruby Jackson',
    personaAge: 29,
    personaPersonality: JSON.stringify(['classic', 'elegant', 'nostalgic']),
    personaBackground: 'Vintage clothing curator and stylist',
    gender: 'female',
    ageRange: 'young',
    ethnicity: 'african',
    bodyType: 'curvy',
    hairStyle: 'vintage curls',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'dark',
    style: 'vintage',
  },

  // ========================================
  // TRADITIONAL (3 presets)
  // ========================================
  {
    name: 'Traditional Indonesian',
    description: 'Elegant in traditional Indonesian batik',
    category: 'traditional',
    imageUrl: '/presets/avatar-creator/traditional-indonesian.jpg',
    thumbnailUrl: '/presets/avatar-creator/traditional-indonesian-thumb.jpg',
    generationPrompt: 'elegant portrait of Indonesian woman in traditional batik kebaya, graceful expression, cultural backdrop',
    personaName: 'Siti Nurhaliza',
    personaAge: 35,
    personaPersonality: JSON.stringify(['graceful', 'cultured', 'elegant']),
    personaBackground: 'Traditional dance instructor and cultural ambassador',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'southeast-asian',
    bodyType: 'average',
    hairStyle: 'traditional updo',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium',
    style: 'traditional-indonesian',
  },
  {
    name: 'Traditional Indian',
    description: 'Elegant in traditional Indian saree',
    category: 'traditional',
    imageUrl: '/presets/avatar-creator/traditional-indian.jpg',
    thumbnailUrl: '/presets/avatar-creator/traditional-indian-thumb.jpg',
    generationPrompt: 'elegant portrait of Indian woman in traditional silk saree, jewelry, graceful pose, cultural setting',
    personaName: 'Lakshmi Devi',
    personaAge: 32,
    personaPersonality: JSON.stringify(['graceful', 'traditional', 'elegant']),
    personaBackground: 'Classical dancer and cultural educator',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'south-asian',
    bodyType: 'average',
    hairStyle: 'long braided',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium-tan',
    style: 'traditional-indian',
  },
  {
    name: 'Traditional Japanese',
    description: 'Elegant in traditional Japanese kimono',
    category: 'traditional',
    imageUrl: '/presets/avatar-creator/traditional-japanese.jpg',
    thumbnailUrl: '/presets/avatar-creator/traditional-japanese-thumb.jpg',
    generationPrompt: 'elegant portrait of Japanese woman in traditional kimono, graceful expression, serene Japanese garden backdrop',
    personaName: 'Yuki Nakamura',
    personaAge: 30,
    personaPersonality: JSON.stringify(['serene', 'graceful', 'traditional']),
    personaBackground: 'Tea ceremony master and cultural preservationist',
    gender: 'female',
    ageRange: 'adult',
    ethnicity: 'east-asian',
    bodyType: 'slim',
    hairStyle: 'traditional updo',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    style: 'traditional-japanese',
  },
]

async function seedAvatarPresets() {
  console.log('🌱 Starting avatar presets seed...')

  try {
    // Check if presets already exist
    const existingCount = await prisma.avatarPreset.count()

    if (existingCount > 0) {
      console.log(`⚠️  Found ${existingCount} existing presets`)
      console.log('⚠️  Skipping seed to avoid duplicates')
      console.log('💡 To re-seed, delete existing presets first:')
      console.log('   npx prisma studio -> Delete all AvatarPreset records')
      return
    }

    // Insert all presets
    console.log(`📦 Inserting ${presets.length} preset avatars...`)

    for (const preset of presets) {
      await prisma.avatarPreset.create({
        data: preset,
      })
      console.log(`  ✅ ${preset.name} (${preset.category})`)
    }

    console.log('\n✨ Avatar presets seed completed!')
    console.log(`📊 Total presets: ${presets.length}`)
    console.log('📊 By category:')
    console.log(`   Professional: ${presets.filter(p => p.category === 'professional').length}`)
    console.log(`   Casual: ${presets.filter(p => p.category === 'casual').length}`)
    console.log(`   Sports: ${presets.filter(p => p.category === 'sports').length}`)
    console.log(`   Fashion: ${presets.filter(p => p.category === 'fashion').length}`)
    console.log(`   Traditional: ${presets.filter(p => p.category === 'traditional').length}`)

    console.log('\n⚠️  Note: Preset images are placeholders')
    console.log('   Generate real images by running:')
    console.log('   npm run generate-preset-images')

  } catch (error) {
    console.error('❌ Error seeding presets:', error)
    throw error
  }
}

// Run seed
seedAvatarPresets()
  .catch((error) => {
    console.error('Fatal error:', error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
